#! /bin/bash
rosrun tue_recorder kinect_recorder name=amigo_top_kinect rec_base_dir=~/ros/rec rgb_topic=/amigo/top_kinect/rgb/image_rect_color depth_topic=/amigo/top_kinect/depth_registered/image_rect rgb_info_topic=/amigo/top_kinect/rgb/camera_info depth_info_topic=/amigo/top_kinect/depth_registered/camera_info
